import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import SocialMedia from '@/components/SocialMedia'
import type { AppProps } from 'next/app'
import '@/styles/globals.scss'
import 'remixicon/fonts/remixicon.css'
import Head from 'next/head'

export default function App({ Component, pageProps }: AppProps) {
  return(
    <>
    <Head>
        <title>Nabraj Chaudhary | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/nlogo.png" />
      </Head>
      <Navbar/>
      <section className="bg-primary px-40 pt-[50px] sm:px-5">
      <Component {...pageProps} />
      <SocialMedia/>
      <Footer/>
      </section>
    </>
  )
}
